In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

/Users/aparandian/Documents/codespaces/pytorch-self-attention/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
class SelfAttention(nn.Module):
    def __init__(self, d_model=2, row_dim = 0, col_dim = 1):
        super().__init__()
        self.d_model = d_model
        self.row_dim = row_dim
        self.col_dim = col_dim
        self.W_Q = nn.Linear(in_features=d_model, out_features=d_model, bias=False)
        self.W_K = nn.Linear(in_features=d_model, out_features=d_model, bias=False)
        self.W_V = nn.Linear(in_features=d_model, out_features=d_model, bias=False)
    
    def forward(self, token_encodings):
        Q = self.W_Q(token_encodings)
        K = self.W_K(token_encodings)
        V = self.W_V(token_encodings)
        
        sims = torch.matmul(Q, K.transpose(-2, -1))
        scaled_sims = sims / (self.d_model ** 0.5)
        attention_weights = F.softmax(scaled_sims, dim=-1)
        output = torch.matmul(attention_weights, V)
        
        return output

In [3]:
encodings_matrix = torch.tensor([
    [1.16,  0.23],
    [0.57, 1.36],
    [4.41, -2.16]
])

torch.manual_seed(42)
self_attention = SelfAttention(d_model = 2, row_dim = 0, col_dim = 1)
self_attention(encodings_matrix)

tensor([[1.0100, 1.0641],
        [0.2040, 0.7057],
        [3.4989, 2.2427]], grad_fn=<MmBackward0>)

In [4]:
self_attention.W_Q.weight.transpose(0, 1)

tensor([[ 0.5406, -0.1657],
        [ 0.5869,  0.6496]], grad_fn=<TransposeBackward0>)

In [5]:
self_attention.W_K.weight.transpose(0, 1)

tensor([[-0.1549, -0.3443],
        [ 0.1427,  0.4153]], grad_fn=<TransposeBackward0>)